# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Marketing Reports
tagline:          'A Tall Cube Report'
description:      'Your online marketing and conversion optimization updates.'
url:              https://tallcube.github.io/milkstork/
baseurl:          /

author:
  name:           'Wes Barton'
  url:            http://www.tallcube.com/

paginate:         1


